version: '2'

services:
    web:
        build:
         context: .
         dockerfile: Dockerfile
        container_name: web
        ports:
         - "8080:80"

    db:
        images: mongo:3.6.1
        container_name: db
        volumes:
         - mongodb:/data/db
         - mondodb_config:/data/configdb
        ports:
         - 27.017:270.17
        command: mongod
    
volumes:
 mongodb:
 mondodb_config: